name: Release
on:
  push:
    tags: ["v*.*.*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: npm
      - run: npm ci
      - run: npm run build --workspaces
      - name: Publish @mrszlv/ai-ui-components
        run: npm publish --workspace @mrszlv/ai-ui-components --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
